// images
export const GET_IMAGES_SAGA = "GET_IMAGES_SAGA";
export const GET_IMAGE_BY_ID_SAGA = "GET_IMAGE_BY_ID_SAGA";
export const SAVE_IMAGE_SAGA = "SAVE_IMAGE_SAGA";
export const UPDATE_IMAGE_SAGA = "UPDATE_IMAGE_SAGA";
export const REMOVE_IMAGE_SAGA = "REMOVE_IMAGE_SAGA";

// animations
export const GET_ANIMATIONS_SAGA = "GET_ANIMATIONS_SAGA";
export const GET_ANIMATION_BY_ID_SAGA = "GET_ANIMATION_BY_ID_SAGA";
export const SAVE_ANIMATION_SAGA = "SAVE_ANIMATION_SAGA";
export const UPDATE_ANIMATION_SAGA = "UPDATE_ANIMATION_SAGA";
export const REMOVE_ANIMATION_SAGA = "REMOVE_ANIMATION_SAGA";

// dragon bones
export const GET_DRAGON_BONES_SAGA = "GET_DRAGON_BONES_SAGA";
export const GET_DRAGON_BONE_BY_ID_SAGA = "GET_DRAGON_BONE_BY_ID_SAGA";
export const SAVE_DRAGON_BONE_SAGA = "SAVE_DRAGON_BONE_SAGA";
export const UPDATE_DRAGON_BONE_SAGA = "UPDATE_DRAGON_BONE_SAGA";
export const REMOVE_DRAGON_BONE_SAGA = "REMOVE_DRAGON_BONE_SAGA";

// audios
export const GET_AUDIOS_SAGA = "GET_AUDIOS_SAGA";
export const GET_AUDIO_BY_ID_SAGA = "GET_AUDIO_BY_ID_SAGA";
export const SAVE_AUDIO_SAGA = "SAVE_AUDIO_SAGA";
export const UPDATE_AUDIO_SAGA = "UPDATE_AUDIO_SAGA";
export const REMOVE_AUDIO_SAGA = "REMOVE_AUDIO_SAGA";

// rules
export const GET_RULES_SAGA = "GET_RULES_SAGA";
export const GET_RULE_BY_ID_SAGA = "GET_RULE_BY_ID_SAGA";
export const SAVE_RULE_SAGA = "SAVE_RULE_SAGA";
export const UPDATE_RULE_SAGA = "UPDATE_RULE_SAGA";
export const REMOVE_RULE_SAGA = "REMOVE_RULE_SAGA";

// layers
export const GET_LAYERS_SAGA = "GET_LAYERS_SAGA";
export const GET_LAYER_BY_ID_SAGA = "GET_LAYER_BY_ID_SAGA";
export const SAVE_LAYER_SAGA = "SAVE_LAYER_SAGA";
export const UPDATE_LAYER_SAGA = "UPDATE_LAYER_SAGA";
export const REMOVE_LAYER_SAGA = "REMOVE_LAYER_SAGA";

// movies
export const GET_MOVIES_SAGA = "GET_MOVIES_SAGA";
export const GET_MOVIE_BY_ID_SAGA = "GET_MOVIE_BY_ID_SAGA";
export const SAVE_MOVIE_SAGA = "SAVE_MOVIE_SAGA";
export const UPDATE_MOVIE_SAGA = "UPDATE_MOVIE_SAGA";
export const REMOVE_MOVIE_SAGA = "REMOVE_MOVIE_SAGA";
