// images
export const ADD_IMAGE_RESOURCE = "ADD_IMAGE_RESOURCE";
export const ADD_IMAGE_RESOURCE_TO_ANIMATION = "ADD_IMAGE_RESOURCE_TO_ANIMATION";
export const UPDATE_IMAGE_NAME = "UPDATE_IMAGE_NAME";
export const UPDATE_IMAGE_URL = "UPDATE_IMAGE_URL";
export const CHANGE_IMAGE_VIEW = "CHANGE_IMAGE_VIEW";
export const CHANGE_IMAGE_PAGE = "CHANGE_IMAGE_PAGE";
export const CHANGE_IMAGE_LIMIT = "CHANGE_IMAGE_LIMIT";
export const CHANGE_IMAGE_SORT = "CHANGE_IMAGE_SORT";
export const CHANGE_IMAGE_FILTER_VALUE = "CHANGE_IMAGE_FILTER_VALUE";
export const SET_IMAGES = "SET_IMAGES";
export const SET_TOTAL_IMAGES_COUNT = "SET_TOTAL_IMAGES_COUNT";
export const SET_IMAGE_FORM = "SET_IMAGE_FORM";
export const CLEAR_IMAGE_FORM = "CLEAR_IMAGE_FORM";
export const PUT_IMAGE_RESOURCE_TO_FORM = "PUT_IMAGE_RESOURCE_TO_FORM";
export const OPEN_OR_CLOSE_IMAGE_MODAL = "OPEN_OR_CLOSE_IMAGE_MODAL";

// animations
export const ADD_ANIMATION_RESOURCE = "ADD_ANIMATION_RESOURCE";
export const UPDATE_ANIMATION_RESOURCE = "UPDATE_ANIMATION_RESOURCE";
export const UPDATE_ANIMATION_NAME = "UPDATE_ANIMATION_NAME";
export const UPDATE_ANIMATION_URL = "UPDATE_ANIMATION_URL";
export const UPDATE_ANIMATION_SPEED = "UPDATE_ANIMATION_SPEED";
export const CHANGE_ANIMATION_VIEW = "CHANGE_ANIMATION_VIEW";
export const CHANGE_ANIMATION_PAGE = "CHANGE_ANIMATION_PAGE";
export const CHANGE_ANIMATION_LIMIT = "CHANGE_ANIMATION_LIMIT";
export const CHANGE_ANIMATION_SORT = "CHANGE_ANIMATION_SORT";
export const CHANGE_ANIMATION_FILTER_VALUE = "CHANGE_ANIMATION_FILTER_VALUE";
export const SET_ANIMATIONS = "SET_ANIMATIONS";
export const SET_ANIMATION_FORM = "SET_ANIMATION_FORM";
export const DELETE_ANIMATION_RESOURCE = "DELETE_ANIMATION_RESOURCE";
export const DELETE_NESTED_IMAGE_RESOURCE = "DELETE_NESTED_IMAGE_RESOURCE";
export const DELETE_IMAGE_FROM_ANIMATION_FORM = "DELETE_IMAGE_FROM_ANIMATION_FORM";
export const SET_TOTAL_ANIMATIONS_COUNT = "SET_TOTAL_ANIMATIONS_COUNT";
export const CLEAR_ANIMATION_FORM = "CLEAR_ANIMATION_FORM";
export const PUT_ANIMATION_RESOURCE_TO_FORM = "PUT_ANIMATION_RESOURCE_TO_FORM";
export const DRAG_AND_DROP_IN_ANIMATION_FORM = "DRAG_AND_DROP_IN_ANIMATION_FORM";

// dragon bones
export const ADD_DRAGON_BONES_RESOURCE = "ADD_DRAGON_BONES_RESOURCE";
export const UPDATE_DRAGON_BONES_RESOURCE = "UPDATE_DRAGON_BONES_RESOURCE";
export const UPDATE_DRAGON_BONES_NAME = "UPDATE_DRAGON_BONES_NAME";
export const UPDATE_TEXTURE = "UPDATE_TEXTURE";
export const UPDATE_TEXTURE_JSON = "UPDATE_TEXTURE_JSON";
export const UPDATE_SKELETON = "UPDATE_SKELETON";
export const CHANGE_DRAGON_BONES_VIEW = "CHANGE_DRAGON_BONES_VIEW";
export const CHANGE_DRAGON_BONES_PAGE = "CHANGE_DRAGON_BONES_PAGE";
export const CHANGE_DRAGON_BONES_LIMIT = "CHANGE_DRAGON_BONES_LIMIT";
export const CHANGE_DRAGON_BONES_SORT = "CHANGE_DRAGON_BONES_SORT";
export const CHANGE_DRAGON_BONES_FILTER_VALUE = "CHANGE_DRAGON_BONES_FILTER_VALUE";
export const DELETE_DRAGON_BONES_RESOURCE = "DELETE_DRAGON_BONES_RESOURCE";
export const CLEAR_DRAGON_BONES_FORM = "CLEAR_DRAGON_BONES_FORM";
export const PUT_DRAGON_BONES_RESOURCE_TO_FORM = "PUT_DRAGON_BONES_RESOURCE_TO_FORM";
export const OPEN_OR_CLOSE_DRAGON_BONES_MODAL = "OPEN_OR_CLOSE_DRAGON_BONES_MODAL";

// audios
export const ADD_AUDIO_RESOURCE = "ADD_AUDIO_RESOURCE";
export const UPDATE_AUDIO_RESOURCE = "UPDATE_AUDIO_RESOURCE";
export const UPDATE_AUDIO_NAME = "UPDATE_AUDIO_NAME";
export const UPDATE_AUDIO_URL = "UPDATE_AUDIO_URL";
export const CHANGE_AUDIO_VIEW = "CHANGE_AUDIO_VIEW";
export const CHANGE_AUDIO_PAGE = "CHANGE_AUDIO_PAGE";
export const CHANGE_AUDIO_LIMIT = "CHANGE_AUDIO_LIMIT";
export const CHANGE_AUDIO_SORT = "CHANGE_AUDIO_SORT";
export const CHANGE_AUDIO_FILTER_VALUE = "CHANGE_AUDIO_FILTER_VALUE";
export const DELETE_AUDIO_RESOURCE = "DELETE_AUDIO_RESOURCE";
export const CLEAR_AUDIO_FORM = "CLEAR_AUDIO_FORM";
export const PUT_AUDIO_RESOURCE_TO_FORM = "PUT_AUDIO_RESOURCE_TO_FORM";
export const OPEN_OR_CLOSE_AUDIO_MODAL = "OPEN_OR_CLOSE_AUDIO_MODAL";
export const CLICK_PLAY_OR_PAUSE = "CLICK_PLAY_OR_PAUSE";

// rules
export const ADD_RULE = "ADD_RULE";
export const UPDATE_RULE = "UPDATE_RULE";
export const UPDATE_RULE_NAME = "UPDATE_RULE_NAME";
export const UPDATE_RULE_COST = "UPDATE_RULE_COST";
export const UPDATE_RULE_CONDITION = "UPDATE_RULE_CONDITION";
export const CHANGE_RULE_VIEW = "CHANGE_RULE_VIEW";
export const CHANGE_RULE_PAGE = "CHANGE_RULE_PAGE";
export const CHANGE_RULE_LIMIT = "CHANGE_RULE_LIMIT";
export const CHANGE_RULE_SORT = "CHANGE_RULE_SORT";
export const CHANGE_RULE_FILTER_VALUE = "CHANGE_RULE_FILTER_VALUE";
export const DELETE_RULE = "DELETE_RULE";
export const CLEAR_RULE_FORM = "CLEAR_RULE_FORM";
export const PUT_RULE_TO_FORM = "PUT_RULE_TO_FORM";
export const OPEN_OR_CLOSE_RULE_MODAL = "OPEN_OR_CLOSE_RULE_MODAL";

// layers
export const ADD_LAYER = "ADD_LAYER";
export const ADD_LAYER_ELEMENT = "ADD_LAYER_ELEMENT";
export const SET_LAYER_SELECTED_ID = "SET_LAYER_SELECTED_ID";
export const UPDATE_LAYER = "UPDATE_LAYER";
export const UPDATE_LAYER_ELEMENT = "UPDATE_LAYER_ELEMENT";
export const UPDATE_LAYER_NAME = "UPDATE_LAYER_NAME";
export const CHANGE_LAYER_PAGE = "CHANGE_LAYER_PAGE";
export const CHANGE_LAYER_LIMIT = "CHANGE_LAYER_LIMIT";
export const CHANGE_LAYER_SORT = "CHANGE_LAYER_SORT";
export const CHANGE_LAYER_FILTER_VALUE = "CHANGE_LAYER_FILTER_VALUE";
export const DELETE_LAYER = "DELETE_LAYER";
export const DELETE_LAYER_ELEMENT = "DELETE_LAYER_ELEMENT";
export const CLEAR_LAYER_FORM = "CLEAR_LAYER_FORM";
export const PUT_LAYER_TO_FORM = "PUT_LAYER_TO_FORM";

// movies
export const SET_MOVIES = "SET_MOVIES";
export const SET_MOVIE_FORM = "SET_MOVIE_FORM";
export const SET_TOTAL_MOVIES_COUNT = "SET_TOTAL_MOVIES_COUNT";
export const CHANGE_MOVIE_PAGE = "CHANGE_MOVIE_PAGE";
export const CHANGE_MOVIE_LIMIT = "CHANGE_MOVIE_LIMIT";
export const CHANGE_MOVIE_SORT = "CHANGE_MOVIE_SORT";
export const CHANGE_MOVIE_FILTER_VALUE = "CHANGE_MOVIE_FILTER_VALUE";
export const CLEAR_MOVIE_FORM = "CLEAR_MOVIE_FORM";

// saga
export const GET_IMAGES_SAGA = "GET_IMAGES_SAGA";
export const GET_IMAGE_BY_ID_SAGA = "GET_IMAGE_BY_ID_SAGA";
export const SAVE_IMAGE_SAGA = "SAVE_IMAGE_SAGA";
export const UPDATE_IMAGE_SAGA = "UPDATE_IMAGE_SAGA";
export const REMOVE_IMAGE_SAGA = "REMOVE_IMAGE_SAGA";

export const GET_ANIMATIONS_SAGA = "GET_ANIMATIONS_SAGA";
export const GET_ANIMATION_BY_ID_SAGA = "GET_ANIMATION_BY_ID_SAGA";

export const GET_MOVIES_SAGA = "GET_MOVIES_SAGA";
export const GET_MOVIE_BY_ID_SAGA = "GET_MOVIE_BY_ID_SAGA";
export const SAVE_MOVIE_SAGA = "SAVE_MOVIE_SAGA";
export const UPDATE_MOVIE_SAGA = "UPDATE_MOVIE_SAGA";
export const REMOVE_MOVIE_SAGA = "REMOVE_MOVIE_SAGA";
