export const ADD_IMAGE_RESOURCE = "ADD_IMAGE_RESOURCE"
export const UPDATE_IMAGE_RESOURCE = "UPDATE_IMAGE_RESOURCE"
export const DELETE_IMAGE_RESOURCE = "DELETE_IMAGE_RESOURCE"

export const UPDATE_IMAGE_NAME = "UPDATE_IMAGE_NAME"
export const UPDATE_IMAGE_URL = "UPDATE_IMAGE_URL"

export const CHANGE_VIEW = "CHANGE_VIEW"
export const IS_OPEN_MODAL = "IS_OPEN_MODAL"
export const PUT_IMAGE_RESOURCE_TO_FORM = "PUT_IMAGE_RESOURCE_TO_FORM"

export const CHANGE_PAGE = "CHANGE_PAGE"
export const CHANGE_LIMIT = "CHANGE_LIMIT"