export const GRID = "GRID";
export const TABLE = "TABLE";

export const ADD_IMAGE_RESOURCE = "ADD_IMAGE_RESOURCE"
export const ADD_ANIMATION_RESOURCE = "ADD_ANIMATION_RESOURCE"
export const ADD_IMAGE_RESOURCE_TO_ANIMATION = "ADD_IMAGE_RESOURCE_TO_ANIMATION"

export const UPDATE_IMAGE_RESOURCE = "UPDATE_IMAGE_RESOURCE"
export const UPDATE_ANIMATION_RESOURCE = "UPDATE_ANIMATION_RESOURCE"

export const DELETE_IMAGE_RESOURCE = "DELETE_IMAGE_RESOURCE"
export const DELETE_ANIMATION_RESOURCE = "DELETE_ANIMATION_RESOURCE"
export const DELETE_NESTED_IMAGE_RESOURCE = "DELETE_NESTED_IMAGE_RESOURCE"
export const DELETE_IMAGE_RESOURCE_FROM_ANIMATION_FORM = "DELETE_IMAGE_RESOURCE_FROM_ANIMATION_FORM"

export const UPDATE_IMAGE_NAME = "UPDATE_IMAGE_NAME"
export const UPDATE_ANIMATION_NAME = "UPDATE_ANIMATION_NAME"

export const UPDATE_IMAGE_URL = "UPDATE_IMAGE_URL"
export const UPDATE_ANIMATION_URL = "UPDATE_ANIMATION_URL"

export const CHANGE_IMAGE_VIEW = "CHANGE_IMAGE_VIEW"
export const CHANGE_ANIMATION_VIEW = "CHANGE_ANIMATION_VIEW"

export const IS_OPEN_IMAGE_MODAL = "IS_OPEN_IMAGE_MODAL"
export const IS_OPEN_ANIMATION_MODAL = "IS_OPEN_ANIMATION_MODAL"

export const PUT_IMAGE_RESOURCE_TO_FORM = "PUT_IMAGE_RESOURCE_TO_FORM"
export const PUT_ANIMATION_RESOURCE_TO_FORM = "PUT_ANIMATION_RESOURCE_TO_FORM"

export const CHANGE_IMAGE_PAGE = "CHANGE_IMAGE_PAGE"
export const CHANGE_ANIMATION_PAGE = "CHANGE_ANIMATION_PAGE"

export const CHANGE_IMAGE_LIMIT = "CHANGE_IMAGE_LIMIT"
export const CHANGE_ANIMATION_LIMIT = "CHANGE_ANIMATION_LIMIT"

export const CHANGE_IMAGE_SORT = "CHANGE_IMAGE_SORT"
export const CHANGE_ANIMATION_SORT = "CHANGE_ANIMATION_SORT"

export const CHANGE_IMAGE_FILTER_VALUE = "CHANGE_IMAGE_FILTER_VALUE"
export const CHANGE_ANIMATION_FILTER_VALUE = "CHANGE_ANIMATION_FILTER_VALUE"

export const DRAG_AND_DROP = "DRAG_AND_DROP"