export const ADD_RESOURCE = "ADD_RESOURCE"
export const DELETE_RESOURCE = "DELETE_RESOURCE"

export const UPDATE_NAME = "UPDATE_NAME"
export const UPDATE_URL = "UPDATE_URL"

export const IS_OPEN_MODAL = "IS_OPEN_MODAL"
export const PUT_IMAGE_RESOURCE_TO_FORM = "PUT_IMAGE_RESOURCE_TO_FORM"

